import mongoose from 'mongoose';

const startupSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  slug: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  tagline: { type: String, default: '' },
  description: { type: String, default: '' },
  logoUrl: { type: String, default: '' },
  coverImageUrl: { type: String, default: '' },
  stage: { type: String, enum: ['Pre-Seed', 'Seed', 'Series A', 'Series B', 'Growth', 'Enterprise'], default: 'Pre-Seed' },
  status: { type: String, enum: ['pending', 'under_review', 'verified', 'rejected', 'suspended'], default: 'pending' },
  isRegisteredCompany: { type: Boolean, default: false },
  registrationNumber: { type: String, default: '' },
  countryOfReg: { type: String, default: '' },
  foundedYear: { type: Number },
  teamSize: { type: Number, default: 1 },
  totalRaised: { type: String, default: '' },
  mrr: { type: String, default: '' },
  websiteUrl: { type: String, default: '' },
  productUrl: { type: String, default: '' },
  pitchDeckUrl: { type: String, default: '' },
  category: { type: String, default: '' },
  subcategory: { type: String, default: '' },
  region: { type: String, default: '' },
  country: { type: String, default: '' },
  city: { type: String, default: '' },
  socialLinkedin: { type: String, default: '' },
  socialTwitter: { type: String, default: '' },
  upvoteCount: { type: Number, default: 0 },
  viewCount: { type: Number, default: 0 },
  isFeatured: { type: Boolean, default: false },
  isTrending: { type: Boolean, default: false },
  initials: { type: String, default: '' },
  color: { type: String, default: '#7C6EFA' },
  tags: [{ type: String }],
  location: { type: String, default: '' },
  flag: { type: String, default: '' },
  raised: { type: String, default: '' },
}, { timestamps: true });

export default mongoose.model('Startup', startupSchema);
